---
deployment:
    tasks:
      - export DEPLOYPATH=/home/sybb0997/public_html/
      - /bin/cp -R public $DEPLOYPATH
      - /bin/cp -R views $DEPLOYPATH
      - /bin/cp app.js $DEPLOYPATH
      - /bin/cp favicon.ico $DEPLOYPATH
      - /bin/cp package.json $DEPLOYPATH
      - /bin/cp package-lock.json $DEPLOYPATH
      - /bin/cp -R node_modules $DEPLOYPATH
      - /bin/cp headshots.json $DEPLOYPATH
      - /bin/cp README.md $DEPLOYPATH
#      - just make it run the npm commands